name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/configure-pages@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Build JupyterLite
        run: |
          cp README.md content
          jupyter lite build --contents content --output-dir dist

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
